/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import exportImportKkm from "export-import-kkm/strapi-admin";
import reports from "../../src/plugins/reports/./admin/src/index.js";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
    "export-import-kkm": exportImportKkm,
    reports: reports,
  },
});
